import datetime
import logging
import random
import re
import time
import urllib.parse
from typing import Any

from bs4 import BeautifulSoup
from curl_cffi import requests as curl_requests

logger = logging.getLogger(__name__)

HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "DNT": "1",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?1",
    "Referer": "https://www.google.com/",
}

LIVE_BLOG_PATTERNS = [
    "livecoverage/",
    "liveblog/",
    "live_updates/",
    "breaking-news/",
    "live/",
]

PAYWALL_DOMAINS = [
    "washingtonpost.com",
    "wsj.com",
    "bloomberg.com",
    "nytimes.com",
    "ft.com",
    "economist.com",
    "businessinsider.com",
    "telegraph.co.uk",
    "thetimes.co.uk",
    "theatlantic.com",
    "newyorker.com",
    "foreignaffairs.com",
    "hbr.org",
]

MAX_RETRIES = 3
BASE_DELAY = 1.0
MIN_DELAY = 1.0
MAX_DELAY = 10.0


def _clean_article_text(raw_text: str) -> str:
    """Remove noise lines (ads, UI prompts, social links) from extracted text."""
    if not raw_text:
        return ""

    skip_patterns = [
        r"^Advertisement$",
        r"^Click here to return to FAST$",
        r"^Read a summary of this article on FAST\.$",
        r"^Get bite-sized news via a new cards interface\. Give it a try\.$",
        r"^Sign up for our newsletters",
        r"^Get the CNA app",
        r"^Get WhatsApp alerts",
        r"^Join our channel for the top reads",
        r"^Subscribe here",
        r"^Download here",
        r"^Join here",
        r"^Also worth reading",
        r"^Content is loading\.\.\.",
        r"^\s*$",
        r"^Show More$",
        r"^Show Less$",
        r"^Expand to read the full story$",
        r"^This audio is generated by an AI tool\.$",
    ]

    compiled = [re.compile(p, re.IGNORECASE) for p in skip_patterns]
    cleaned_lines: list[str] = []

    for line in raw_text.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue
        if any(p.match(stripped) for p in compiled):
            continue
        cleaned_lines.append(stripped)

    cleaned_text = "\n".join(cleaned_lines).strip()
    return re.sub(r"\n{3,}", "\n\n", cleaned_text)


def _get_body_text(html: str) -> str:
    """Extract article body text from HTML, preferring >100 chars of real text."""
    soup = BeautifulSoup(html, "html.parser")

    for tag in soup(["script", "style", "nav", "footer", "header"]):
        tag.decompose()

    selectors = [
        "article",
        "article .article-body",
        "article .post-content",
        "article .entry-content",
        "article .post-body",
        "article .content",
        "article p",
        ".post-content",
        ".entry-content",
        ".post-body",
        ".content",
        "#post-body",
        "#article-body",
        "#content",
        "#main-content",
        "main",
        ".article-body",
        ".article",
        ".story-content",
        "[role='main']",
    ]

    for selector in selectors:
        elements = soup.select(selector)
        if elements:
            text_parts = []
            for el in elements:
                text = el.get_text(separator="\n", strip=True)
                if text and len(text) > 50:
                    text_parts.append(text)
            return "\n".join(text_parts)

    # Fallback: first <article> or <div> with >100 direct text chars
    for tag_name in ("article", "div", "section"):
        tag = soup.find(tag_name)
        if tag:
            text = tag.get_text(separator="\n", strip=True)
            links_only = re.sub(r"\[.*?\]", "", text)
            if len(links_only) > 100:
                return text

    # Last resort: strip nav/footer/header and take remaining text
    for tag_name in ("nav", "footer", "header", "aside"):
        for el in soup.find_all(tag_name):
            el.decompose()
    return soup.get_text(separator="\n", strip=True)


def _determine_parser(url: str) -> str:
    """Classify parsing method based on domain."""
    parts = url.lower().split("://")[1].split("/")
    domain = parts[0] if parts else ""
    if "reuters.com" in domain:
        return "reuters"
    if "bbc" in domain:
        return "bbc"
    return "generic"


def _is_live_blog(url: str) -> bool:
    """Check if URL is a live blog page that shouldn't be enriched."""
    if "://" not in url:
        return False
    path = url.lower().split("://")[1].split("/")[2] if len(url.lower().split("://")[1].split("/")) > 2 else ""
    domain = url.lower().split("://")[1].split("/")[0]
    return any(p in domain or p in path for p in LIVE_BLOG_PATTERNS)


def is_paywall_url(url: str) -> bool:
    """Return True if the URL belongs to a known paywall domain."""
    if not url:
        return False
    parsed = urllib.parse.urlparse(url)
    domain = parsed.netloc.lower()
    if domain.startswith("www."):
        domain = domain[4:]
    return any(domain == pw or domain.endswith(f".{pw}") for pw in PAYWALL_DOMAINS)


def _normalize_url(url: str) -> str:
    """Normalize URL to https:// and remove trailing slash."""
    url = url.replace("http://", "https://")
    return url.rstrip("/")


def _retry_with_backoff(url: str, headers: dict, timeout: int = 30) -> str:
    """Make a request with retry logic and exponential backoff.

    Args:
        url: URL to fetch.
        headers: Request headers.
        timeout: Request timeout in seconds.

    Returns:
        Response text as a string.

    Raises:
        Exception: If all retries fail.
    """
    last_exception: Exception | None = None
    session = curl_requests.Session(impersonate="chrome120", headers=headers)

    for attempt in range(MAX_RETRIES):
        try:
            response = session.get(url, timeout=timeout, allow_redirects=True)
            status = response.status_code

            if status == 451:
                raise Exception("Geo-blocked (451)")
            if status == 401:
                raise Exception("Unauthorized (401)")
            if status in (403, 429):
                impersonates = ["chrome110", "edge101", "safari15_5"]
                session.impersonate = impersonates[attempt % len(impersonates)]
                if attempt < MAX_RETRIES - 1:
                    delay = min(
                        BASE_DELAY * (2 ** attempt) + random.uniform(0, 0.5),
                        MAX_DELAY,
                    )
                    logger.debug("Backing off %0.1fs for %s", delay, url[:60])
                    time.sleep(delay)
                    continue
                else:
                    raise Exception(f"HTTP {status} after retries")

            response.raise_for_status()
            content_type = response.headers.get("content-type", "").lower()
            if "text/html" not in content_type:
                raise Exception(f"Non-HTML response: {content_type}")

            return response.text

        except Exception as exc:
            last_exception = exc
            logger.debug("Attempt %d failed for %s: %s", attempt + 1, url[:60], exc)
            if attempt < MAX_RETRIES - 1:
                delay = min(
                    BASE_DELAY * (2 ** attempt) + random.uniform(0, 0.5),
                    MAX_DELAY,
                )
                time.sleep(delay)

    raise Exception(f"All {MAX_RETRIES} retries failed: {last_exception}")


def enrich_articles(articles: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Enrich a list of article dicts with full_text via BeautifulSoup.

    Modifies articles in place and returns the list.

    Args:
        articles: List of article dicts with 'url' keys.

    Returns:
        The same list with enriched fields populated.
    """
    for article in articles:
        url = article.get("url", "")
        if not url:
            continue

        enrichment_attempted = False
        enrichment_success = False
        full_text = ""
        parsing_method = ""
        enriched_at = ""

        # Skip paywalls immediately
        if is_paywall_url(url):
            parsing_method = "paywall_skipped"
            article["full_text"] = full_text
            article["enrichment_attempted"] = enrichment_attempted
            article["enrichment_success"] = enrichment_success
            article["parsing_method"] = parsing_method
            article["enriched_at"] = enriched_at
            logger.debug("Skipped paywall URL: %s", url[:80])
            continue

        # Skip live blog pages
        if _is_live_blog(url):
            parsing_method = "live_blog_skipped"
            article["full_text"] = full_text
            article["enrichment_attempted"] = enrichment_attempted
            article["enrichment_success"] = enrichment_success
            article["parsing_method"] = parsing_method
            article["enriched_at"] = enriched_at
            logger.debug("Skipped live blog URL: %s", url[:80])
            continue

        try:
            enrichment_attempted = True

            html = _retry_with_backoff(url, HEADERS, timeout=30)
            raw_text = _get_body_text(html)
            parsing_method = _determine_parser(url)
            if raw_text:
                cleaned = _clean_article_text(raw_text)
                if len(cleaned) > 100:
                    full_text = cleaned
                    enrichment_success = True
                else:
                    enrichment_success = False
            else:
                enrichment_success = False

            if not enrichment_success and len(full_text) > 0:
                logger.warning(
                    "Partial enrichment for %s: %d chars", url[:60], len(full_text)
                )
        except Exception as exc:
            enrichment_attempted = True
            enrichment_success = False
            parsing_method = ""
            if "403" in str(exc) or "Cloudflare" in str(exc):
                logger.debug("Enrichment blocked (likely bot protection) for %s", url[:60])
            elif "paywall" in str(exc).lower():
                logger.debug("Enrichment blocked by paywall for %s", url[:60])
            else:
                logger.warning("Enrichment failed for %s: %s", url[:80], exc)

        enriched_at = datetime.datetime.now(datetime.timezone.utc).isoformat()

        article["full_text"] = full_text
        article["enrichment_attempted"] = enrichment_attempted
        article["enrichment_success"] = enrichment_success
        article["parsing_method"] = parsing_method
        article["enriched_at"] = enriched_at

    return articles
